A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/enzo/IA_trading/IA.py", line 16, in <module>
    from tensorflow.keras.models import Sequential, load_model
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/eager/context.py", line 38, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/client/pywrap_tf_session.py", line 23, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/enzo/IA_trading/IA.py", line 16, in <module>
    from tensorflow.keras.models import Sequential, load_model
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/__init__.py", line 46, in <module>
    from tensorflow.python import data
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/experimental/__init__.py", line 98, in <module>
    from tensorflow.python.data.experimental import service
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 374, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 27, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 20, in <module>
    from tensorflow.python.data.util import structure
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/util/structure.py", line 26, in <module>
    from tensorflow.python.data.util import nest
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/util/nest.py", line 40, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/framework/sparse_tensor.py", line 28, in <module>
    from tensorflow.python.framework import constant_op
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/framework/constant_op.py", line 29, in <module>
    from tensorflow.python.eager import execute
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/eager/execute.py", line 27, in <module>
    from tensorflow.python.framework import dtypes
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/framework/dtypes.py", line 30, in <module>
    from tensorflow.python.lib.core import _pywrap_bfloat16
AttributeError: _ARRAY_API not found
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/Users/enzo/IA_trading/IA.py", line 16, in <module>
    from tensorflow.keras.models import Sequential, load_model
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/__init__.py", line 46, in <module>
    from tensorflow.python import data
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/experimental/__init__.py", line 98, in <module>
    from tensorflow.python.data.experimental import service
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 374, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 27, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 20, in <module>
    from tensorflow.python.data.util import structure
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/util/structure.py", line 26, in <module>
    from tensorflow.python.data.util import nest
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/util/nest.py", line 40, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/framework/sparse_tensor.py", line 28, in <module>
    from tensorflow.python.framework import constant_op
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/framework/constant_op.py", line 29, in <module>
    from tensorflow.python.eager import execute
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/eager/execute.py", line 27, in <module>
    from tensorflow.python.framework import dtypes
  File "/Users/enzo/Library/Python/3.9/lib/python/site-packages/tensorflow/python/framework/dtypes.py", line 33, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
        () -> handle
